language: rust
sudo: false
cache:
  directories:
    - /home/travis/.cargo
rust: nightly
os:
  - linux
  - osx
before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 11
  - nvm use 11
  - node -v
  - npm -v
install:
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-web
  - cargo install clippy
jobs:
  include:
    - stage: build
      script: cargo web build --target=wasm32-unknown-unknown
    - stage: test
      script: cargo web test --target=wasm32-unknown-unknown --nodejs
    - stage: lint
      script: cargo clippy


before_cache:
  - rm -rf /home/travis/.cargo/registry
