language: rust
sudo: false
cache:
  directories:
    - /home/travis/.cargo
rust: nightly
os:
  - linux
  - osx
before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 11
  - nvm use 11
  - node -v
  - npm -v
install:
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-web || true
  - rustup component add clippy-preview || true
script:
  - cargo web build --target=wasm32-unknown-unknown
  - cargo web test --target=wasm32-unknown-unknown --nodejs
  - cargo +nightly clippy -Z unstable-options


before_cache:
  - rm -rf /home/travis/.cargo/registry
